---
title: "p8105_hw5_mfc2162"
author: "Madeline Cannon"
date: "11/3/2019"
output: github_document
---

## Problem 1

#### Load data and introduce missing values

```{r}

library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

```


#### Function to fill missing values

```{r}

fill_missing = function(vector) {
  if (is.numeric(vector)) {
    v_mean = mean(vector, na.rm=TRUE)
    vector[is.na(vector)] = v_mean
  }
  if (is.character(vector)) {
    vector[is.na(vector)] = "virginica"
  }
  return(vector)
}

```


#### Apply to dataset using map

```{r}

iris_with_missing = map_df(iris_with_missing, fill_missing)
iris_with_missing

```


## Problem 2

#### Read in data for each subject

```{r}

files = list.files("./data")
study = data.frame()

get_data = function(file_name) {
  path = paste("./data/", file_name, sep = "")
  subject_data = read_csv(path)
  row = cbind(file_name, subject_data)
  study = rbind(study, row)
}

wide = map_dfr(files, get_data)

```


#### Tidy data

```{r}

study = wide %>%
  pivot_longer(week_1:week_8,
               names_to = "week",
               names_prefix = "week_",
               values_to = "observation") %>%
  mutate(id = substr(file_name, start = 5, stop = 6),
         arm = substr(file_name, start = 1, stop = 3),
         week = as.numeric(week)) %>%
  select(id, arm, week, observation)

study

```


#### Spaghetti plots

```{r}

control = study %>% filter(arm == "con")
experimental = study %>% filter(arm == "exp")

ggplot(data = control, aes(x = week, y = observation, color = id)) +
  geom_line() + xlab("Week") + ylab("Observation") + labs(color = "Subject ID") +
  ggtitle("Control")

ggplot(data = experimental, aes(x = week, y = observation, color = id)) +
  geom_line() + xlab("Week") + ylab("Observation") + labs(color = "Subject ID") +
  ggtitle("Experimental")

```

In the control group, the observations do not appear to change with time. In the experimental group, the observations clearly increase over time.


## Problem 3

```{r}

set.seed(1)

sim_regression = function(n = 30, beta0 = 2, beta1) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 0, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, 50)
  )
  
  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta1_hat = coef(ls_fit)[2]
  )
}

sim_results = 
  rerun(10000, sim_regression(30, 2, 0)) %>% 
  bind_rows()

```